#!/usr/bin/env python3
"""BALLPARK question-bank expansion batch.

Rules this batch follows (so every generated question can be defended):
  * INTEGER answers only - the slider steps by whole numbers, so a fractional
    "true answer" would be unreachable and the revealed answer would be a
    rounding, not a fact.
  * STABLE facts only - unit conversions, fixed counts, and settled history.
    No "tallest / richest / current record / current population" items, which
    expire and would silently become wrong answers.
  * The answer is never placed on a slider edge, and every question carries a
    real reveal note.

Tuple layout: (category, question, unit, answer, min, max, note)
"""
NEW = [
    # ---------------- Geography ----------------
    ("Geography", "How many continents are there on Earth?", "continents", 7, 0, 15, "Seven, by the standard model."),
    ("Geography", "How many countries are there in South America?", "countries", 12, 0, 30, "12 sovereign states."),
    ("Geography", "How many countries does the Prime Meridian pass through?", "countries", 8, 0, 20, "Eight, excluding Antarctica."),
    ("Geography", "How many member states are in the United Nations?", "members", 193, 0, 300, "193, as of 2024."),
    ("Geography", "How many Great Lakes are there in North America?", "lakes", 5, 0, 15, "Five: Superior, Michigan, Huron, Erie, Ontario."),
    ("Geography", "How many countries make up Central America?", "countries", 7, 0, 20, "Seven."),
    ("Geography", "How many boroughs does New York City have?", "boroughs", 5, 0, 15, "Five."),
    ("Geography", "How many countries share a land border with the USA?", "countries", 2, 0, 10, "Canada and Mexico."),
    ("Geography", "How many countries border Brazil?", "countries", 10, 0, 20, "Ten."),
    ("Geography", "How many US states begin with the letter M?", "states", 8, 0, 20, "Eight."),
    ("Geography", "How many nations are in the G7?", "nations", 7, 0, 20, "Seven."),
    ("Geography", "How tall is Mount Kilimanjaro, in metres?", "metres", 5895, 0, 8000, "5,895 m."),
    ("Geography", "How many member states are in the European Union?", "countries", 27, 0, 40, "27, as of 2024."),
    ("Geography", "How many official time zones does Australia span?", "time zones", 3, 0, 10, "Three."),
    ("Geography", "How many counties are in the US state of Texas?", "counties", 254, 0, 500, "254, the most of any state."),
    ("Geography", "How many countries sit on the Iberian Peninsula?", "countries", 2, 0, 10, "Spain and Portugal."),
    ("Geography", "How many states are in Australia?", "states", 6, 0, 15, "Six states, plus mainland territories."),
    ("Geography", "How many provinces are in Canada?", "provinces", 10, 0, 20, "Ten, plus three territories."),
    ("Geography", "How many regions is Italy divided into?", "regions", 20, 0, 40, "Twenty."),
    ("Geography", "How many countries border Germany?", "countries", 9, 0, 20, "Nine."),
    ("Geography", "How long is the Panama Canal, in km?", "km", 82, 0, 200, "About 82 km."),
    ("Geography", "How many states are in Mexico?", "states", 31, 0, 60, "31, plus Mexico City."),
    ("Geography", "How many member states are in the African Union?", "members", 55, 0, 80, "55."),
    ("Geography", "How many countries does the Danube flow through?", "countries", 10, 0, 20, "Ten."),
    ("Geography", "How many member countries are in NATO?", "members", 32, 0, 50, "32, as of 2024."),
    ("Geography", "How many US states border the Pacific Ocean?", "states", 5, 0, 15, "Five, counting Alaska and Hawaii."),

    # ---------------- Human body ----------------
    ("Human body", "How many muscles are in the human body?", "muscles", 600, 0, 1500, "About 600."),
    ("Human body", "How many ribs does a typical adult human have?", "ribs", 24, 0, 50, "24, in 12 pairs."),
    ("Human body", "How many vertebrae are in the human spine?", "vertebrae", 33, 0, 60, "33 in total; some fuse in adults."),
    ("Human body", "How many pairs of chromosomes do humans have?", "pairs", 23, 0, 50, "23."),
    ("Human body", "How many baby teeth does a typical child have?", "teeth", 20, 0, 50, "Twenty primary teeth."),
    ("Human body", "How many bones are in the human skull?", "bones", 22, 0, 60, "22."),
    ("Human body", "How many litres of blood are in an average adult human?", "litres", 5, 0, 15, "About 5."),
    ("Human body", "How many basic tastes can the human tongue detect?", "tastes", 5, 0, 10, "Five: sweet, sour, salty, bitter, umami."),
    ("Human body", "How many small bones are in the human ear?", "bones", 3, 0, 10, "Three ossicles."),
    ("Human body", "Roughly how many genes are in the human genome, in thousands?", "thousand", 20, 0, 60, "Roughly 20,000."),
    ("Human body", "How many bones does a newborn baby have?", "bones", 270, 0, 500, "About 270; many fuse later."),
    ("Human body", "Roughly how many neurons are in the human brain, in billions?", "billion", 86, 0, 200, "About 86 billion."),
    ("Human body", "What is normal human body temperature, in Celsius?", "degrees C", 37, 0, 60, "About 37."),
    ("Human body", "How many hours of sleep is an adult advised to get per night?", "hours", 8, 0, 20, "Around 8."),

    # ---------------- Science & units ----------------
    ("Science", "How many elements are in the periodic table?", "elements", 118, 0, 250, "118."),
    ("Science", "What is the boiling point of water at sea level, in Celsius?", "degrees C", 100, 0, 300, "100."),
    ("Science", "What is absolute zero, in Celsius?", "degrees C", -273, -600, 100, "-273.15."),
    ("Science", "How many protons does a carbon atom have?", "protons", 6, 0, 20, "Six."),
    ("Science", "What is the freezing point of water, in Fahrenheit?", "degrees F", 32, 0, 150, "32."),
    ("Science", "How many inches are in a foot?", "inches", 12, 0, 40, "Twelve."),
    ("Science", "How many inches are in a yard?", "inches", 36, 0, 100, "Thirty-six."),
    ("Science", "How many feet are in a mile?", "feet", 5280, 0, 12000, "5,280."),
    ("Science", "How many metres are in a mile?", "metres", 1609, 0, 5000, "About 1,609."),
    ("Science", "How many metres are in a kilometre?", "metres", 1000, 0, 3000, "1,000."),
    ("Science", "How many centimetres are in a metre?", "cm", 100, 0, 300, "100."),
    ("Science", "How many millimetres are in a metre?", "mm", 1000, 0, 3000, "1,000."),
    ("Science", "How many kilograms are in a metric ton?", "kg", 1000, 0, 5000, "1,000."),
    ("Science", "How many grams are in a kilogram?", "grams", 1000, 0, 3000, "1,000."),
    ("Science", "How many ounces are in a pound?", "ounces", 16, 0, 50, "Sixteen."),
    ("Science", "How many pounds are in a stone?", "pounds", 14, 0, 40, "Fourteen."),
    ("Science", "How many pounds are in a US ton?", "pounds", 2000, 0, 6000, "2,000."),
    ("Science", "How many pints are in a US gallon?", "pints", 8, 0, 30, "Eight."),
    ("Science", "How many cups are in a US gallon?", "cups", 16, 0, 50, "Sixteen."),
    ("Science", "How many fluid ounces are in a US cup?", "ounces", 8, 0, 30, "Eight."),
    ("Science", "How many tablespoons are in a US cup?", "tablespoons", 16, 0, 50, "Sixteen."),
    ("Science", "How many teaspoons are in a tablespoon?", "teaspoons", 3, 0, 12, "Three."),
    ("Science", "How many millilitres are in a teaspoon?", "ml", 5, 0, 20, "About 5."),
    ("Science", "How many degrees are in a right angle?", "degrees", 90, 0, 200, "90."),
    ("Science", "How many degrees are in a full circle?", "degrees", 360, 0, 720, "360."),
    ("Science", "What do the interior angles of a triangle add up to, in degrees?", "degrees", 180, 0, 400, "180."),
    ("Science", "How many sides does a hexagon have?", "sides", 6, 0, 20, "Six."),
    ("Science", "How many sides does a decagon have?", "sides", 10, 0, 30, "Ten."),
    ("Science", "How many sides does a dodecagon have?", "sides", 12, 0, 40, "Twelve."),
    ("Science", "How many faces does a cube have?", "faces", 6, 0, 20, "Six."),
    ("Science", "How many edges does a cube have?", "edges", 12, 0, 40, "Twelve."),
    ("Science", "How many vertices does a cube have?", "vertices", 8, 0, 20, "Eight."),
    ("Science", "What is the atomic number of gold?", "atomic number", 79, 0, 150, "79."),
    ("Science", "What is the atomic number of hydrogen?", "atomic number", 1, 0, 20, "One."),
    ("Science", "What is the atomic number of oxygen?", "atomic number", 8, 0, 30, "Eight."),
    ("Science", "How many bits are in a byte?", "bits", 8, 0, 20, "Eight."),
    ("Science", "How many bytes are in a kibibyte?", "bytes", 1024, 0, 3000, "1,024."),
    ("Science", "How many megabytes are in a gigabyte?", "MB", 1024, 0, 3000, "1,024 (binary convention)."),

    # ---------------- Animals & nature ----------------
    ("Animals", "How many legs does an insect have?", "legs", 6, 0, 20, "Six."),
    ("Animals", "How many legs does a crab have?", "legs", 10, 0, 30, "Ten, including its claws."),
    ("Animals", "How many teeth does an adult dog have?", "teeth", 42, 0, 100, "42."),
    ("Animals", "How many teeth does an adult cat have?", "teeth", 30, 0, 80, "30."),
    ("Animals", "How many wings does a butterfly have?", "wings", 4, 0, 12, "Four."),
    ("Animals", "How many arms does an octopus have?", "arms", 8, 0, 20, "Eight."),
    ("Animals", "How many limbs does a squid have, arms plus tentacles?", "limbs", 10, 0, 30, "Eight arms plus two tentacles."),
    ("Animals", "How many eyes does a typical spider have?", "eyes", 8, 0, 20, "Most spiders have eight."),
    ("Animals", "How many species of penguin are there?", "species", 18, 0, 50, "18, widely cited."),
    ("Animals", "How many humps does a Bactrian camel have?", "humps", 2, 0, 6, "Two."),
    ("Animals", "How many legs does a lobster have?", "legs", 10, 0, 30, "Ten."),
    ("Animals", "How many bones does a shark have?", "bones", 0, 0, 50, "None: sharks are cartilaginous."),
    ("Animals", "How many wings does a dragonfly have?", "wings", 4, 0, 12, "Four."),
    ("Animals", "How many days does a chicken egg take to hatch?", "days", 21, 0, 60, "About 21."),
    ("Animals", "How many days is human gestation?", "days", 280, 0, 500, "About 280."),
    ("Animals", "How many hearts does a squid have?", "hearts", 3, 0, 10, "Three."),

    # ---------------- Sport ----------------
    ("Sport", "How many players are on a basketball court, both teams?", "players", 10, 0, 30, "Ten."),
    ("Sport", "How many players are on a volleyball court, both teams?", "players", 12, 0, 30, "Twelve."),
    ("Sport", "How many players are in a cricket team?", "players", 11, 0, 30, "Eleven."),
    ("Sport", "How many players are in a rugby union team?", "players", 15, 0, 40, "Fifteen."),
    ("Sport", "How many players per American football team are on the field?", "players", 11, 0, 30, "Eleven."),
    ("Sport", "How many rings are on the Olympic flag?", "rings", 5, 0, 15, "Five."),
    ("Sport", "How many players per baseball team are on the field?", "players", 9, 0, 25, "Nine."),
    ("Sport", "How many sets must you win a best-of-five tennis match?", "sets", 3, 0, 10, "Three."),
    ("Sport", "How many points is a basketball free throw worth?", "points", 1, 0, 6, "One."),
    ("Sport", "How many points is a basketball three-pointer worth?", "points", 3, 0, 10, "Three."),
    ("Sport", "How many periods are in an ice hockey game?", "periods", 3, 0, 10, "Three."),
    ("Sport", "How many quarters are in an NBA game?", "quarters", 4, 0, 12, "Four."),
    ("Sport", "How many innings are in a standard baseball game?", "innings", 9, 0, 20, "Nine."),
    ("Sport", "How many metres long is a marathon?", "metres", 42195, 0, 100000, "42,195."),
    ("Sport", "How many players are in a netball team?", "players", 7, 0, 20, "Seven."),
    ("Sport", "How many players per water polo team are in the pool?", "players", 7, 0, 20, "Seven."),
    ("Sport", "How many metres long is an Olympic swimming pool?", "metres", 50, 0, 100, "Fifty."),
    ("Sport", "How many players are in a field hockey team?", "players", 11, 0, 30, "Eleven."),
    ("Sport", "How many balls are used in a snooker frame?", "balls", 22, 0, 50, "22."),
    ("Sport", "How many red balls are on a snooker table?", "balls", 15, 0, 30, "Fifteen."),
    ("Sport", "How many pins are in a standard game of bowling?", "pins", 10, 0, 30, "Ten."),
    ("Sport", "How many frames are in a standard game of bowling?", "frames", 10, 0, 30, "Ten."),

    # ---------------- Food ----------------
    ("Food", "How many calories are in a teaspoon of sugar?", "calories", 16, 0, 60, "About 16."),
    ("Food", "How many calories are in a large egg?", "calories", 70, 0, 200, "About 70."),
    ("Food", "How many millilitres are in a standard wine bottle?", "ml", 750, 0, 2000, "750."),
    ("Food", "How many grams are in a US stick of butter?", "grams", 113, 0, 500, "About 113."),
    ("Food", "How many ounces are in a US soda can?", "ounces", 12, 0, 40, "12."),
    ("Food", "How many calories are in a slice of white bread?", "calories", 80, 0, 300, "Typically about 80."),
    ("Food", "How many calories are in a medium banana?", "calories", 105, 0, 300, "About 105."),
    ("Food", "What is the safe internal temperature for chicken, in Celsius?", "degrees C", 74, 0, 200, "74 (165 F)."),

    # ---------------- Time ----------------
    ("Time", "How many days are in a leap year?", "days", 366, 0, 800, "366."),
    ("Time", "How many weeks are in a year?", "weeks", 52, 0, 100, "52."),
    ("Time", "How many months have 31 days?", "months", 7, 0, 12, "Seven."),
    ("Time", "How many hours are in a week?", "hours", 168, 0, 400, "168."),
    ("Time", "How many seconds are in an hour?", "seconds", 3600, 0, 10000, "3,600."),
    ("Time", "How many days are in a fortnight?", "days", 14, 0, 40, "Fourteen."),
    ("Time", "How many days are in a standard year?", "days", 365, 0, 800, "365."),
    ("Time", "How many years are in a millennium?", "years", 1000, 0, 3000, "1,000."),
    ("Time", "How many minutes are in a day?", "minutes", 1440, 0, 4000, "1,440."),
    ("Time", "How many seconds are in a week?", "seconds", 604800, 0, 1500000, "604,800."),
    ("Time", "How many days does Mars take to orbit the Sun?", "days", 687, 0, 1500, "About 687 Earth days."),
    ("Time", "How many days does Mercury take to orbit the Sun?", "days", 88, 0, 400, "About 88."),
    ("Time", "How many weeks long is a typical pregnancy?", "weeks", 40, 0, 60, "About 40."),

    # ---------------- Space ----------------
    ("Space", "How many moons does Earth have?", "moons", 1, 0, 6, "One."),
    ("Space", "How many moons does Mars have?", "moons", 2, 0, 10, "Two: Phobos and Deimos."),
    ("Space", "How many planets in the Solar System have rings?", "planets", 4, 0, 12, "Four: Jupiter, Saturn, Uranus, Neptune."),
    ("Space", "How many constellations are officially recognised?", "constellations", 88, 0, 200, "88."),
    ("Space", "How many dwarf planets does the IAU officially recognise?", "planets", 5, 0, 20, "Five: Pluto, Ceres, Eris, Haumea, Makemake."),
    ("Space", "How many Apollo missions landed people on the Moon?", "missions", 6, 0, 20, "Six."),
    ("Space", "What is the diameter of the Earth, in km?", "km", 12742, 0, 40000, "About 12,742."),
    ("Space", "How many thousand miles is the Moon from Earth?", "thousand miles", 239, 0, 1000, "About 239,000 miles."),
    ("Space", "How many moons does Venus have?", "moons", 0, 0, 6, "None."),

    # ---------------- History ----------------
    ("History", "How many years did World War II last?", "years", 6, 0, 20, "About six."),
    ("History", "In what year did the Berlin Wall fall?", "year", 1989, 1900, 2000, "1989."),
    ("History", "In what year did people first land on the Moon?", "year", 1969, 1900, 2000, "1969."),
    ("History", "In what year did World War I begin?", "year", 1914, 1800, 2000, "1914."),
    ("History", "How many amendments does the US Constitution have?", "amendments", 27, 0, 60, "27."),
    ("History", "How many people signed the US Declaration of Independence?", "people", 56, 0, 150, "56."),
    ("History", "How many wives did Henry VIII have?", "wives", 6, 0, 12, "Six."),
    ("History", "How many colonies declared independence in 1776?", "colonies", 13, 0, 40, "Thirteen."),
    ("History", "How many years did Queen Victoria reign?", "years", 63, 0, 100, "63, from 1837 to 1901."),
    ("History", "How many years did Queen Elizabeth II reign?", "years", 70, 0, 120, "70."),
    ("History", "How many lines are in a Shakespearean sonnet?", "lines", 14, 0, 40, "Fourteen."),
    ("History", "How many basic Roman numerals are there?", "numerals", 7, 0, 20, "Seven: I, V, X, L, C, D, M."),
    ("History", "In what year was the first iPhone released?", "year", 2007, 1950, 2020, "2007."),
    ("History", "In what year was the Chernobyl disaster?", "year", 1986, 1900, 2000, "1986."),
    ("History", "In what year did the Wright brothers first fly?", "year", 1903, 1800, 2000, "1903."),
    ("History", "How many years did the Hundred Years' War last?", "years", 116, 0, 300, "About 116."),

    # ---------------- Everyday ----------------
    ("Everyday", "How many sides does a stop sign have?", "sides", 8, 0, 20, "Eight."),
    ("Everyday", "How many cards are in a standard deck, without jokers?", "cards", 52, 0, 120, "52."),
    ("Everyday", "How many suits are in a standard deck of cards?", "suits", 4, 0, 12, "Four."),
    ("Everyday", "How many cards are in each suit of a standard deck?", "cards", 13, 0, 30, "Thirteen."),
    ("Everyday", "How many dominoes are in a double-six set?", "dominoes", 28, 0, 60, "28."),
    ("Everyday", "How many pieces does each player start with in chess?", "pieces", 16, 0, 40, "Sixteen."),
    ("Everyday", "How many letters are in the English alphabet?", "letters", 26, 0, 60, "26."),
    ("Everyday", "How many letters are in the word antidisestablishmentarianism?", "letters", 28, 0, 60, "28."),
    ("Everyday", "How many colours are traditionally in a rainbow?", "colours", 7, 0, 20, "Seven."),
    ("Everyday", "How many strings does a concert harp have?", "strings", 47, 0, 100, "47."),
    ("Everyday", "How many strings does a standard bass guitar have?", "strings", 4, 0, 12, "Four."),
    ("Everyday", "How many points is the letter Q worth in Scrabble?", "points", 10, 0, 20, "Ten."),
    ("Everyday", "How many tiles does each player start with in Scrabble?", "tiles", 7, 0, 20, "Seven."),
    ("Everyday", "How many tiles are in a Scrabble set?", "tiles", 100, 0, 300, "100."),
    ("Everyday", "How many squares are on a Monopoly board?", "squares", 40, 0, 100, "Forty."),
    ("Everyday", "Roughly how many strings does a grand piano have?", "strings", 230, 0, 600, "Around 230."),
    ("Everyday", "How many notes are in a chromatic scale, one octave?", "notes", 12, 0, 30, "Twelve."),
    ("Everyday", "How many lines are on a musical staff?", "lines", 5, 0, 15, "Five."),
    ("Everyday", "How many symphonies did Beethoven complete?", "symphonies", 9, 0, 20, "Nine."),
    ("Everyday", "How many letters are in the Greek alphabet?", "letters", 24, 0, 60, "24."),
    ("Everyday", "How many letters are in supercalifragilisticexpialidocious?", "letters", 34, 0, 80, "34."),
    ("Everyday", "How many letters are in pneumonoultramicroscopicsilicovolcanoconiosis?", "letters", 45, 0, 80, "45."),

    # ---------------- Transport & landmarks ----------------
    ("Transport", "How many engines does a Boeing 747 have?", "engines", 4, 0, 10, "Four."),
    ("Transport", "About how many people were aboard the Titanic?", "people", 2200, 0, 5000, "About 2,200."),
    ("Transport", "About how many stations are on the London Underground?", "stations", 272, 0, 600, "About 272."),
    ("Transport", "What is the maximum scheduled length of a Formula 1 race, in minutes?", "minutes", 120, 0, 300, "Two hours."),
    ("Landmarks", "How many steps are there to the top of the Eiffel Tower?", "steps", 1665, 0, 4000, "1,665."),
    ("Landmarks", "How many floors does the Empire State Building have?", "floors", 102, 0, 300, "102."),
    ("Landmarks", "How many steps lead to the crown of the Statue of Liberty?", "steps", 354, 0, 1000, "354."),
    ("Landmarks", "How many sides does the Pentagon have?", "sides", 5, 0, 15, "Five."),
    ("Landmarks", "How many rooms are in the White House?", "rooms", 132, 0, 300, "132."),
    ("Landmarks", "How many public levels does the Eiffel Tower have?", "levels", 3, 0, 15, "Three."),

    # ---------------- Earth ----------------
    ("Earth", "What is the average surface temperature of the Earth, in Celsius?", "degrees C", 15, -30, 60, "About 15."),
    ("Earth", "How many km is the Earth's circumference at the equator?", "km", 40075, 0, 100000, "About 40,075."),
    ("Earth", "What percentage of the Earth's surface is covered by water?", "percent", 71, 0, 100, "About 71."),
]
